name: Build-Playground

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    # Build & Publish
    - run: dotnet restore
    - run: dotnet publish -c Release ./src/Qulaly.Web.Playground/Qulaly.Web.Playground.csproj

    - name: Publish to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: src/Qulaly.Web.Playground/bin/Release/netstandard2.1/publish/wwwroot/
